using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using UnityEngine;
using KSP;
using Strategies;

namespace ReStrategia
{
    public abstract class KerbinProgram : StrategiaStrategy { }
    public class KerbinProgram0 : KerbinProgram { }
    public class KerbinProgram1 : KerbinProgram { }

    public abstract class MoonProgram : StrategiaStrategy { }
    public class MoonProgram0 : MoonProgram { }
    public class MoonProgram1 : MoonProgram { }
    public class MoonProgram2 : MoonProgram { }
    public class MoonProgram3 : MoonProgram { }
    public class MoonProgram4 : MoonProgram { }
    public class MoonProgram5 : MoonProgram { }
    public class MoonProgram6 : MoonProgram { }
    public class MoonProgram7 : MoonProgram { }
    public class MoonProgram8 : MoonProgram { }
    public class MoonProgram9 : MoonProgram { }
    public class MoonProgram10 : MoonProgram { }
    public class MoonProgram11 : MoonProgram { }
    public class MoonProgram12 : MoonProgram { }
    public class MoonProgram13 : MoonProgram { }
    public class MoonProgram14 : MoonProgram { }
    public class MoonProgram15 : MoonProgram { }
    public class MoonProgram16 : MoonProgram { }
    public class MoonProgram17 : MoonProgram { }
    public class MoonProgram18 : MoonProgram { }
    public class MoonProgram19 : MoonProgram { }

    public abstract class PlanetaryProgram : StrategiaStrategy { }
    public class PlanetaryProgram0 : PlanetaryProgram { }
    public class PlanetaryProgram1 : PlanetaryProgram { }
    public class PlanetaryProgram2 : PlanetaryProgram { }
    public class PlanetaryProgram3 : PlanetaryProgram { }
    public class PlanetaryProgram4 : PlanetaryProgram { }
    public class PlanetaryProgram5 : PlanetaryProgram { }
    public class PlanetaryProgram6 : PlanetaryProgram { }
    public class PlanetaryProgram7 : PlanetaryProgram { }
    public class PlanetaryProgram8 : PlanetaryProgram { }
    public class PlanetaryProgram9 : PlanetaryProgram { }
    public class PlanetaryProgram10 : PlanetaryProgram { }
    public class PlanetaryProgram11 : PlanetaryProgram { }
    public class PlanetaryProgram12 : PlanetaryProgram { }
    public class PlanetaryProgram13 : PlanetaryProgram { }
    public class PlanetaryProgram14 : PlanetaryProgram { }
    public class PlanetaryProgram15 : PlanetaryProgram { }
    public class PlanetaryProgram16 : PlanetaryProgram { }
    public class PlanetaryProgram17 : PlanetaryProgram { }
    public class PlanetaryProgram18 : PlanetaryProgram { }
    public class PlanetaryProgram19 : PlanetaryProgram { }
    public class PlanetaryProgram20 : PlanetaryProgram { }
    public class PlanetaryProgram21 : PlanetaryProgram { }
    public class PlanetaryProgram22 : PlanetaryProgram { }
    public class PlanetaryProgram23 : PlanetaryProgram { }
    public class PlanetaryProgram24 : PlanetaryProgram { }
    public class PlanetaryProgram25 : PlanetaryProgram { }
    public class PlanetaryProgram26 : PlanetaryProgram { }
    public class PlanetaryProgram27 : PlanetaryProgram { }
    public class PlanetaryProgram28 : PlanetaryProgram { }
    public class PlanetaryProgram29 : PlanetaryProgram { }
    public class PlanetaryProgram30 : PlanetaryProgram { }
    public class PlanetaryProgram31 : PlanetaryProgram { }
    public class PlanetaryProgram32 : PlanetaryProgram { }
    public class PlanetaryProgram33 : PlanetaryProgram { }
    public class PlanetaryProgram34 : PlanetaryProgram { }
    public class PlanetaryProgram35 : PlanetaryProgram { }
    public class PlanetaryProgram36 : PlanetaryProgram { }
    public class PlanetaryProgram37 : PlanetaryProgram { }
    public class PlanetaryProgram38 : PlanetaryProgram { }
    public class PlanetaryProgram39 : PlanetaryProgram { }
    public class PlanetaryProgram40 : PlanetaryProgram { }
    public class PlanetaryProgram41 : PlanetaryProgram { }
    public class PlanetaryProgram42 : PlanetaryProgram { }
    public class PlanetaryProgram43 : PlanetaryProgram { }
    public class PlanetaryProgram44 : PlanetaryProgram { }
    public class PlanetaryProgram45 : PlanetaryProgram { }
    public class PlanetaryProgram46 : PlanetaryProgram { }
    public class PlanetaryProgram47 : PlanetaryProgram { }
    public class PlanetaryProgram48 : PlanetaryProgram { }
    public class PlanetaryProgram49 : PlanetaryProgram { }
    public class PlanetaryProgram50 : PlanetaryProgram { }
    public class PlanetaryProgram51 : PlanetaryProgram { }
    public class PlanetaryProgram52 : PlanetaryProgram { }
    public class PlanetaryProgram53 : PlanetaryProgram { }
    public class PlanetaryProgram54 : PlanetaryProgram { }
    public class PlanetaryProgram55 : PlanetaryProgram { }
    public class PlanetaryProgram56 : PlanetaryProgram { }
    public class PlanetaryProgram57 : PlanetaryProgram { }
    public class PlanetaryProgram58 : PlanetaryProgram { }
    public class PlanetaryProgram59 : PlanetaryProgram { }
    public class PlanetaryProgram60 : PlanetaryProgram { }
    public class PlanetaryProgram61 : PlanetaryProgram { }
    public class PlanetaryProgram62 : PlanetaryProgram { }
    public class PlanetaryProgram63 : PlanetaryProgram { }
    public class PlanetaryProgram64 : PlanetaryProgram { }
    public class PlanetaryProgram65 : PlanetaryProgram { }
    public class PlanetaryProgram66 : PlanetaryProgram { }
    public class PlanetaryProgram67 : PlanetaryProgram { }
    public class PlanetaryProgram68 : PlanetaryProgram { }
    public class PlanetaryProgram69 : PlanetaryProgram { }
    public class PlanetaryProgram70 : PlanetaryProgram { }
    public class PlanetaryProgram71 : PlanetaryProgram { }
    public class PlanetaryProgram72 : PlanetaryProgram { }
    public class PlanetaryProgram73 : PlanetaryProgram { }
    public class PlanetaryProgram74 : PlanetaryProgram { }
    public class PlanetaryProgram75 : PlanetaryProgram { }
    public class PlanetaryProgram76 : PlanetaryProgram { }
    public class PlanetaryProgram77 : PlanetaryProgram { }
    public class PlanetaryProgram78 : PlanetaryProgram { }
    public class PlanetaryProgram79 : PlanetaryProgram { }
    public class PlanetaryProgram80 : PlanetaryProgram { }
    public class PlanetaryProgram81 : PlanetaryProgram { }
    public class PlanetaryProgram82 : PlanetaryProgram { }
    public class PlanetaryProgram83 : PlanetaryProgram { }
    public class PlanetaryProgram84 : PlanetaryProgram { }
    public class PlanetaryProgram85 : PlanetaryProgram { }
    public class PlanetaryProgram86 : PlanetaryProgram { }
    public class PlanetaryProgram87 : PlanetaryProgram { }
    public class PlanetaryProgram88 : PlanetaryProgram { }
    public class PlanetaryProgram89 : PlanetaryProgram { }
    public class PlanetaryProgram90 : PlanetaryProgram { }
    public class PlanetaryProgram91 : PlanetaryProgram { }
    public class PlanetaryProgram92 : PlanetaryProgram { }
    public class PlanetaryProgram93 : PlanetaryProgram { }
    public class PlanetaryProgram94 : PlanetaryProgram { }
    public class PlanetaryProgram95 : PlanetaryProgram { }
    public class PlanetaryProgram96 : PlanetaryProgram { }
    public class PlanetaryProgram97 : PlanetaryProgram { }
    public class PlanetaryProgram98 : PlanetaryProgram { }
    public class PlanetaryProgram99 : PlanetaryProgram { }
    public class PlanetaryProgram100 : PlanetaryProgram { }
    public class PlanetaryProgram101 : PlanetaryProgram { }
    public class PlanetaryProgram102 : PlanetaryProgram { }
    public class PlanetaryProgram103 : PlanetaryProgram { }
    public class PlanetaryProgram104 : PlanetaryProgram { }
    public class PlanetaryProgram105 : PlanetaryProgram { }
    public class PlanetaryProgram106 : PlanetaryProgram { }
    public class PlanetaryProgram107 : PlanetaryProgram { }
    public class PlanetaryProgram108 : PlanetaryProgram { }
    public class PlanetaryProgram109 : PlanetaryProgram { }
    public class PlanetaryProgram110 : PlanetaryProgram { }
    public class PlanetaryProgram111 : PlanetaryProgram { }
    public class PlanetaryProgram112 : PlanetaryProgram { }
    public class PlanetaryProgram113 : PlanetaryProgram { }
    public class PlanetaryProgram114 : PlanetaryProgram { }
    public class PlanetaryProgram115 : PlanetaryProgram { }
    public class PlanetaryProgram116 : PlanetaryProgram { }
    public class PlanetaryProgram117 : PlanetaryProgram { }
    public class PlanetaryProgram118 : PlanetaryProgram { }
    public class PlanetaryProgram119 : PlanetaryProgram { }
    public class PlanetaryProgram120 : PlanetaryProgram { }
    public class PlanetaryProgram121 : PlanetaryProgram { }
    public class PlanetaryProgram122 : PlanetaryProgram { }
    public class PlanetaryProgram123 : PlanetaryProgram { }
    public class PlanetaryProgram124 : PlanetaryProgram { }
    public class PlanetaryProgram125 : PlanetaryProgram { }
    public class PlanetaryProgram126 : PlanetaryProgram { }
    public class PlanetaryProgram127 : PlanetaryProgram { }
    public class PlanetaryProgram128 : PlanetaryProgram { }
    public class PlanetaryProgram129 : PlanetaryProgram { }
    public class PlanetaryProgram130 : PlanetaryProgram { }
    public class PlanetaryProgram131 : PlanetaryProgram { }
    public class PlanetaryProgram132 : PlanetaryProgram { }
    public class PlanetaryProgram133 : PlanetaryProgram { }
    public class PlanetaryProgram134 : PlanetaryProgram { }
    public class PlanetaryProgram135 : PlanetaryProgram { }
    public class PlanetaryProgram136 : PlanetaryProgram { }
    public class PlanetaryProgram137 : PlanetaryProgram { }
    public class PlanetaryProgram138 : PlanetaryProgram { }
    public class PlanetaryProgram139 : PlanetaryProgram { }
    public class PlanetaryProgram140 : PlanetaryProgram { }
    public class PlanetaryProgram141 : PlanetaryProgram { }
    public class PlanetaryProgram142 : PlanetaryProgram { }
    public class PlanetaryProgram143 : PlanetaryProgram { }
    public class PlanetaryProgram144 : PlanetaryProgram { }
    public class PlanetaryProgram145 : PlanetaryProgram { }
    public class PlanetaryProgram146 : PlanetaryProgram { }
    public class PlanetaryProgram147 : PlanetaryProgram { }
    public class PlanetaryProgram148 : PlanetaryProgram { }
    public class PlanetaryProgram149 : PlanetaryProgram { }
    public class PlanetaryProgram150 : PlanetaryProgram { }
    public class PlanetaryProgram151 : PlanetaryProgram { }
    public class PlanetaryProgram152 : PlanetaryProgram { }
    public class PlanetaryProgram153 : PlanetaryProgram { }
    public class PlanetaryProgram154 : PlanetaryProgram { }
    public class PlanetaryProgram155 : PlanetaryProgram { }
    public class PlanetaryProgram156 : PlanetaryProgram { }
    public class PlanetaryProgram157 : PlanetaryProgram { }
    public class PlanetaryProgram158 : PlanetaryProgram { }
    public class PlanetaryProgram159 : PlanetaryProgram { }
    public class PlanetaryProgram160 : PlanetaryProgram { }
    public class PlanetaryProgram161 : PlanetaryProgram { }
    public class PlanetaryProgram162 : PlanetaryProgram { }
    public class PlanetaryProgram163 : PlanetaryProgram { }
    public class PlanetaryProgram164 : PlanetaryProgram { }
    public class PlanetaryProgram165 : PlanetaryProgram { }
    public class PlanetaryProgram166 : PlanetaryProgram { }
    public class PlanetaryProgram167 : PlanetaryProgram { }
    public class PlanetaryProgram168 : PlanetaryProgram { }
    public class PlanetaryProgram169 : PlanetaryProgram { }
    public class PlanetaryProgram170 : PlanetaryProgram { }
    public class PlanetaryProgram171 : PlanetaryProgram { }
    public class PlanetaryProgram172 : PlanetaryProgram { }
    public class PlanetaryProgram173 : PlanetaryProgram { }
    public class PlanetaryProgram174 : PlanetaryProgram { }
    public class PlanetaryProgram175 : PlanetaryProgram { }
    public class PlanetaryProgram176 : PlanetaryProgram { }
    public class PlanetaryProgram177 : PlanetaryProgram { }
    public class PlanetaryProgram178 : PlanetaryProgram { }
    public class PlanetaryProgram179 : PlanetaryProgram { }
    public class PlanetaryProgram180 : PlanetaryProgram { }
    public class PlanetaryProgram181 : PlanetaryProgram { }
    public class PlanetaryProgram182 : PlanetaryProgram { }
    public class PlanetaryProgram183 : PlanetaryProgram { }
    public class PlanetaryProgram184 : PlanetaryProgram { }
    public class PlanetaryProgram185 : PlanetaryProgram { }
    public class PlanetaryProgram186 : PlanetaryProgram { }
    public class PlanetaryProgram187 : PlanetaryProgram { }
    public class PlanetaryProgram188 : PlanetaryProgram { }
    public class PlanetaryProgram189 : PlanetaryProgram { }
    public class PlanetaryProgram190 : PlanetaryProgram { }
    public class PlanetaryProgram191 : PlanetaryProgram { }
    public class PlanetaryProgram192 : PlanetaryProgram { }
    public class PlanetaryProgram193 : PlanetaryProgram { }
    public class PlanetaryProgram194 : PlanetaryProgram { }
    public class PlanetaryProgram195 : PlanetaryProgram { }
    public class PlanetaryProgram196 : PlanetaryProgram { }
    public class PlanetaryProgram197 : PlanetaryProgram { }
    public class PlanetaryProgram198 : PlanetaryProgram { }
    public class PlanetaryProgram199 : PlanetaryProgram { }

    public abstract class GasGiantProgram : StrategiaStrategy { }
    public class GasGiantProgram0 : GasGiantProgram { }
    public class GasGiantProgram1 : GasGiantProgram { }
    public class GasGiantProgram2 : GasGiantProgram { }
    public class GasGiantProgram3 : GasGiantProgram { }
    public class GasGiantProgram4 : GasGiantProgram { }
    public class GasGiantProgram5 : GasGiantProgram { }
    public class GasGiantProgram6 : GasGiantProgram { }
    public class GasGiantProgram7 : GasGiantProgram { }
    public class GasGiantProgram8 : GasGiantProgram { }
    public class GasGiantProgram9 : GasGiantProgram { }
    public class GasGiantProgram10 : GasGiantProgram { }
    public class GasGiantProgram11 : GasGiantProgram { }
    public class GasGiantProgram12 : GasGiantProgram { }
    public class GasGiantProgram13 : GasGiantProgram { }
    public class GasGiantProgram14 : GasGiantProgram { }
    public class GasGiantProgram15 : GasGiantProgram { }
    public class GasGiantProgram16 : GasGiantProgram { }
    public class GasGiantProgram17 : GasGiantProgram { }
    public class GasGiantProgram18 : GasGiantProgram { }
    public class GasGiantProgram19 : GasGiantProgram { }
    public class GasGiantProgram20 : GasGiantProgram { }
    public class GasGiantProgram21 : GasGiantProgram { }
    public class GasGiantProgram22 : GasGiantProgram { }
    public class GasGiantProgram23 : GasGiantProgram { }
    public class GasGiantProgram24 : GasGiantProgram { }
    public class GasGiantProgram25 : GasGiantProgram { }
    public class GasGiantProgram26 : GasGiantProgram { }
    public class GasGiantProgram27 : GasGiantProgram { }
    public class GasGiantProgram28 : GasGiantProgram { }
    public class GasGiantProgram29 : GasGiantProgram { }
    public class GasGiantProgram30 : GasGiantProgram { }
    public class GasGiantProgram31 : GasGiantProgram { }
    public class GasGiantProgram32 : GasGiantProgram { }
    public class GasGiantProgram33 : GasGiantProgram { }
    public class GasGiantProgram34 : GasGiantProgram { }
    public class GasGiantProgram35 : GasGiantProgram { }
    public class GasGiantProgram36 : GasGiantProgram { }
    public class GasGiantProgram37 : GasGiantProgram { }
    public class GasGiantProgram38 : GasGiantProgram { }
    public class GasGiantProgram39 : GasGiantProgram { }
    public class GasGiantProgram40 : GasGiantProgram { }
    public class GasGiantProgram41 : GasGiantProgram { }
    public class GasGiantProgram42 : GasGiantProgram { }
    public class GasGiantProgram43 : GasGiantProgram { }
    public class GasGiantProgram44 : GasGiantProgram { }
    public class GasGiantProgram45 : GasGiantProgram { }
    public class GasGiantProgram46 : GasGiantProgram { }
    public class GasGiantProgram47 : GasGiantProgram { }
    public class GasGiantProgram48 : GasGiantProgram { }
    public class GasGiantProgram49 : GasGiantProgram { }
    public class GasGiantProgram50 : GasGiantProgram { }
    public class GasGiantProgram51 : GasGiantProgram { }
    public class GasGiantProgram52 : GasGiantProgram { }
    public class GasGiantProgram53 : GasGiantProgram { }
    public class GasGiantProgram54 : GasGiantProgram { }
    public class GasGiantProgram55 : GasGiantProgram { }
    public class GasGiantProgram56 : GasGiantProgram { }
    public class GasGiantProgram57 : GasGiantProgram { }
    public class GasGiantProgram58 : GasGiantProgram { }
    public class GasGiantProgram59 : GasGiantProgram { }
    public class GasGiantProgram60 : GasGiantProgram { }
    public class GasGiantProgram61 : GasGiantProgram { }
    public class GasGiantProgram62 : GasGiantProgram { }
    public class GasGiantProgram63 : GasGiantProgram { }
    public class GasGiantProgram64 : GasGiantProgram { }
    public class GasGiantProgram65 : GasGiantProgram { }
    public class GasGiantProgram66 : GasGiantProgram { }
    public class GasGiantProgram67 : GasGiantProgram { }
    public class GasGiantProgram68 : GasGiantProgram { }
    public class GasGiantProgram69 : GasGiantProgram { }
    public class GasGiantProgram70 : GasGiantProgram { }
    public class GasGiantProgram71 : GasGiantProgram { }
    public class GasGiantProgram72 : GasGiantProgram { }
    public class GasGiantProgram73 : GasGiantProgram { }
    public class GasGiantProgram74 : GasGiantProgram { }
    public class GasGiantProgram75 : GasGiantProgram { }
    public class GasGiantProgram76 : GasGiantProgram { }
    public class GasGiantProgram77 : GasGiantProgram { }
    public class GasGiantProgram78 : GasGiantProgram { }
    public class GasGiantProgram79 : GasGiantProgram { }
    public class GasGiantProgram80 : GasGiantProgram { }
    public class GasGiantProgram81 : GasGiantProgram { }
    public class GasGiantProgram82 : GasGiantProgram { }
    public class GasGiantProgram83 : GasGiantProgram { }
    public class GasGiantProgram84 : GasGiantProgram { }
    public class GasGiantProgram85 : GasGiantProgram { }
    public class GasGiantProgram86 : GasGiantProgram { }
    public class GasGiantProgram87 : GasGiantProgram { }
    public class GasGiantProgram88 : GasGiantProgram { }
    public class GasGiantProgram89 : GasGiantProgram { }
    public class GasGiantProgram90 : GasGiantProgram { }
    public class GasGiantProgram91 : GasGiantProgram { }
    public class GasGiantProgram92 : GasGiantProgram { }
    public class GasGiantProgram93 : GasGiantProgram { }
    public class GasGiantProgram94 : GasGiantProgram { }
    public class GasGiantProgram95 : GasGiantProgram { }
    public class GasGiantProgram96 : GasGiantProgram { }
    public class GasGiantProgram97 : GasGiantProgram { }
    public class GasGiantProgram98 : GasGiantProgram { }
    public class GasGiantProgram99 : GasGiantProgram { }
}
